# Generated by Django 4.2.7 on 2023-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_singlemenuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_table',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
