# Generated by Django 4.2.7 on 2023-11-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_delete_table_booking_no_of_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
